apiVersion: batch/v1
kind: Job
metadata:
  name: match-add-job
spec:
  completions: 3 # will run 3 pods
  parallelism: 3 # will start those three 3 at once
  template:
    spec:
      containers:
        - name: match-add
          image: ubuntu
          command: ['expr', '3','+','2']
      restartPolicy: Never
