apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: challenge1
    tier: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        name: wordpress
        app: challenge1
    spec:
      containers:
      - name: wordpress-container
        image: wordpress
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        volumeMounts:
        -  name: wordpress-persistent-storage
           mountPath: "/var/www/html"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-persistent-storage
  replicas: 2
  selector:
    matchLabels:
      name: wordpress
      app: challenge1